- name: Install sccache
  uses: mozilla-actions/sccache-action@v0.0.9

- name: Configure sccache for macOS builds
  if: ${{ runner.os == 'macOS' }}
  run: |
    echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
    echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
